categorias:
  - Problema em saque
  - Atendimento ruim
  - Fraude bancária
  - Cobrança indevida
  - Cartão clonado
  - PIX enviado errado
  - Problema com fatura do cartão
  - Problema com limite de crédito
  - Problema no acesso ao app
  - Débito não autorizado

openai:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 512
  model: gpt-4o

prompt_classificacao: |
  Analise o seguinte histórico de atendimento e realize as seguintes tarefas:

  1. Classifique o problema principal em uma das seguintes categorias:
  - {categorias}

  2. Gere um resumo detalhado do histórico, destacando os principais pontos e possíveis problemas.

  Cada atualização no histórico é separada por "###".

  Histórico:
  ### {historico}

  Responda no seguinte formato:
  Classificação: <categoria>
  Resumo: <resumo>  